/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.PhonesDao;
import dao.UserDao;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.User;
import java.awt.event.KeyEvent;

/**
 *
 * @author William
 */
public class UsersPage extends javax.swing.JFrame {
    
    DefaultTableModel tableModel = new DefaultTableModel();

    /**
     * Creates new form UsersPage
     */
    public UsersPage() {
        initComponents();
        setLocationRelativeTo(null);
        addColumns();
        RetrieveUser();
        setTitle("USERS MANAGEMENT");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        userLocation = new javax.swing.JTextField();
        userPhoneId = new javax.swing.JTextField();
        insertBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        phoneViewBtn = new javax.swing.JButton();
        logOutBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        usersTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setText("User Name");

        jLabel2.setText("User Location");

        jLabel3.setText("User Phone Id");

        userName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameActionPerformed(evt);
            }
        });
        userName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                userNameKeyTyped(evt);
            }
        });

        userLocation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                userLocationKeyTyped(evt);
            }
        });

        userPhoneId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                userPhoneIdKeyTyped(evt);
            }
        });

        insertBtn.setBackground(new java.awt.Color(0, 128, 0));
        insertBtn.setForeground(new java.awt.Color(255, 255, 255));
        insertBtn.setText("Insert");
        insertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertBtnActionPerformed(evt);
            }
        });

        updateBtn.setBackground(new java.awt.Color(0, 0, 139));
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(139, 0, 0));
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        phoneViewBtn.setBackground(new java.awt.Color(173, 216, 230));
        phoneViewBtn.setText("Phone View");
        phoneViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneViewBtnActionPerformed(evt);
            }
        });

        logOutBtn.setBackground(new java.awt.Color(139, 0, 0));
        logOutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logOutBtn.setText("Log Out");
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Access Hub");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(insertBtn)
                                .addGap(48, 48, 48)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userPhoneId, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(updateBtn)
                                .addGap(46, 46, 46)
                                .addComponent(deleteBtn)
                                .addGap(40, 40, 40)
                                .addComponent(phoneViewBtn)))
                        .addGap(0, 141, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(173, 173, 173)
                        .addComponent(logOutBtn)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(logOutBtn))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(userLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(userPhoneId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertBtn)
                    .addComponent(updateBtn)
                    .addComponent(deleteBtn)
                    .addComponent(phoneViewBtn))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        usersTable.setBackground(new java.awt.Color(200, 220, 230));
        usersTable.setForeground(new java.awt.Color(0, 0, 128));
        usersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        usersTable.setGridColor(new java.awt.Color(220, 230, 240));
        usersTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usersTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(usersTable);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Users");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void insertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertBtnActionPerformed
         boolean isValid = Validation();
        if(isValid)
            InsertUser();
        ClearFields();
    }//GEN-LAST:event_insertBtnActionPerformed

    private void phoneViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneViewBtnActionPerformed
       AdminPage aP = new AdminPage();
       aP.setVisible(true);
       dispose();
    }//GEN-LAST:event_phoneViewBtnActionPerformed

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        LoginPage lP = new LoginPage();
        lP.setVisible(true);
        dispose();
    }//GEN-LAST:event_logOutBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
         boolean isValid = Validation();
        if(isValid)
            DeleteUser();
        ClearFields();
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
         boolean isValid = Validation();
        if(isValid)
            UpdateUser();
        ClearFields();
    }//GEN-LAST:event_updateBtnActionPerformed

    private void usersTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersTableMouseClicked
        int selectedRowIndex = usersTable.getSelectedRow();

        userName.setText(tableModel.getValueAt(selectedRowIndex, 1).toString());
        userLocation.setText(tableModel.getValueAt(selectedRowIndex, 2).toString());
        userPhoneId.setText(tableModel.getValueAt(selectedRowIndex, 3).toString());
    }//GEN-LAST:event_usersTableMouseClicked

    private void userNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameActionPerformed
        
    }//GEN-LAST:event_userNameActionPerformed

    private void userNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userNameKeyTyped
        char keyChar = evt.getKeyChar();
        boolean digit = Character.isDigit(keyChar);
        if(digit){
            evt.consume();
        }
    }//GEN-LAST:event_userNameKeyTyped

    private void userLocationKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userLocationKeyTyped
         char keyChar = evt.getKeyChar();
        boolean digit = Character.isDigit(keyChar);
        if(digit){
            evt.consume();
        }
    }//GEN-LAST:event_userLocationKeyTyped

    private void userPhoneIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userPhoneIdKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_userPhoneIdKeyTyped

    private void addColumns() {
        tableModel.addColumn("User Id");
        tableModel.addColumn("User Name");
        tableModel.addColumn("User Location");
        tableModel.addColumn("User Phone");

        usersTable.setModel(tableModel);
    }
    
     private boolean Validation() {
        if(userName.getText().trim().isEmpty() 
                || userLocation.getText().trim().isEmpty() 
                || userPhoneId.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Fill all the fields", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
     
     
    private void InsertUser() {
        User userObj = new User();
        userObj.setUserName(userName.getText());
        userObj.setUserLocation(userLocation.getText());
        userObj.setUserPhone(Integer.parseInt(userPhoneId.getText()));
        

        UserDao dao = new UserDao();
        int rowsAffected = dao.InsertUser(userObj);
        
        PhonesDao phDao = new PhonesDao();
        int phonesRows = phDao.UpdatePhones(Integer.parseInt(userPhoneId.getText()));
        
        if (rowsAffected > 0){
            JOptionPane.showMessageDialog(this, "User recorded successfully!", "Success",
                    JOptionPane.INFORMATION_MESSAGE);

            tableModel = new DefaultTableModel();
            addColumns();
            RetrieveUser();
            return;
        }else{
            JOptionPane.showMessageDialog(this,
                    "Something went wrong!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
    }
     
    
    private void DeleteUser() {
        int option = JOptionPane.showConfirmDialog(this,
                "You are about to permanently delete this record!",
                "Warning",
                JOptionPane.YES_NO_CANCEL_OPTION);
        if(option == 0) System.out.println("Alright!");
        else return;

        //making a phonedao object and passing in the phone mode object and the phone id
        UserDao ud = new UserDao();
        int selectedRowIndex = usersTable.getSelectedRow();
        int rows = ud.DeleteUser(Integer.parseInt(tableModel.getValueAt(selectedRowIndex, 0).toString()));

        if(rows > 0) {
            JOptionPane.showMessageDialog(this,
                    "Record deleted",
                    "Information",
                    JOptionPane.INFORMATION_MESSAGE);
        }

        tableModel = new DefaultTableModel();
        addColumns();
        RetrieveUser();
    }
     
     private void UpdateUser() {
         //A simple warning before executing the event
        int option = JOptionPane.showConfirmDialog(this,
                "You are about to permanently modify this record!",
                "Warning",
                JOptionPane.YES_NO_CANCEL_OPTION);
        if(option == 0) System.out.println("Alright");
        else return;
        //Making a phone model object
        User user = new User();
        user.setUserName(userName.getText());
        user.setUserLocation(userLocation.getText());
        user.setUserPhone(Integer.parseInt(userPhoneId.getText()));
        
        //making a phone object and passing in the phone mode object and the phone id
        UserDao dao = new UserDao();
        int selectedRowIndex = usersTable.getSelectedRow();
        int rowsAffected = dao.UpdateUser(user, Integer.parseInt(tableModel.getValueAt(selectedRowIndex, 0).toString()));

        if(rowsAffected > 0) {
            JOptionPane.showMessageDialog(this,
                    "Record Updated", "Information", JOptionPane.INFORMATION_MESSAGE);
        }

        //this is for refreshing so that the jtable reflects the updated data
        tableModel = new DefaultTableModel();
        addColumns();
        RetrieveUser();
    }
    
    private void RetrieveUser() {
        UserDao dao = new UserDao();
        dao.RetrieveUser(tableModel);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsersPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsersPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsersPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsersPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsersPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton insertBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JButton phoneViewBtn;
    private javax.swing.JButton updateBtn;
    private javax.swing.JTextField userLocation;
    private javax.swing.JTextField userName;
    private javax.swing.JTextField userPhoneId;
    private javax.swing.JTable usersTable;
    // End of variables declaration//GEN-END:variables


    
    private void ClearFields() {
        userName.setText("");
        userLocation.setText("");
        userPhoneId.setText("");
    }




}